In [1]:
import pandas as pd
import numpy as np

In [13]:
df = pd.read_csv("../data/global_freelancers_raw.csv")

In [14]:
df.head()

,freelancer_ID,name,gender,age,country,language,primary_skill,years_of_experience,hourly_rate (USD),rating,is_active,client_satisfaction
0,FL250001,Ms. Nicole Kidd,f,52.0,Italy,Italian,Blockchain Development,11.0,100,NaN,0,NaN
1,FL250002,Vanessa Garcia,FEMALE,52.0,Australia,English,Mobile Apps,34.0,USD 100,3.3,1,84%
2,FL250003,Juan Nelson,male,53.0,Germany,German,Graphic Design,31.0,50,0.0,N,71%
3,FL250004,Amanda Spencer,F,38.0,Australia,English,Web Development,4.0,$40,1.5,N,90%
4,FL250005,Lynn Curtis DDS,female,53.0,Germany,German,Web Development,27.0,30,4.8,0,83%

In [15]:
df.shape

(1000, 12)

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   freelancer_ID        1000 non-null   str
 1   name                 1000 non-null   str
 2   gender               1000 non-null   str
 3   age                  970 non-null    float64
 4   country              1000 non-null   str
 5   language             1000 non-null   str
 6   primary_skill        1000 non-null   str
 7   years_of_experience  949 non-null    float64
 8   hourly_rate (USD)    906 non-null    str
 9   rating               899 non-null    float64
 10  is_active            911 non-null    str
 11  client_satisfaction  824 non-null    str
dtypes: float64(3), str(9)
memory usage: 93.9 KB

In [17]:
df.describe()

              age  years_of_experience      rating
count  970.000000           949.000000  899.000000
mean    40.509278            11.340358    2.512570
std     11.942605             9.680610    1.546599
min     20.000000             0.000000    0.000000
25%     31.000000             3.000000    1.400000
50%     41.000000             9.000000    2.600000
75%     51.000000            17.000000    3.800000
max     60.000000            41.000000    5.000000

In [18]:
df.isnull().sum()

freelancer_ID            0
name                     0
gender                   0
age                     30
country                  0
language                 0
primary_skill            0
years_of_experience     51
hourly_rate (USD)       94
rating                 101
is_active               89
client_satisfaction    176
dtype: int64

In [19]:
df.duplicated().sum()

np.int64(0)

In [20]:
df.columns = df.columns.str.strip()

In [21]:
df.columns = df.columns.str.lower()

In [22]:
df.columns

Index(['freelancer_id', 'name', 'gender', 'age', 'country', 'language',
       'primary_skill', 'years_of_experience', 'hourly_rate (usd)', 'rating',
       'is_active', 'client_satisfaction'],
      dtype='str')

In [23]:
df['gender'].value_counts()

gender
FEMALE    115
M         106
f         103
Male      103
MALE      102
male      100
m          99
Female     96
F          90
female     86
Name: count, dtype: int64

In [25]:
df['gender'] = df['gender'].str.strip().str.lower()
df['gender'] = df['gender'].replace({
    'f': 'female',
    'm': 'male'
})

In [26]:
df['gender'].value_counts()

gender
male      510
female    490
Name: count, dtype: int64

In [27]:
df['is_active'].value_counts(dropna=False)

is_active
1        190
0        182
N         98
False     97
Y         94
NaN       89
no        88
yes       85
True      77
Name: count, dtype: int64

In [33]:
df.columns = df.columns.str.strip().str.lower()

In [34]:
df.columns = df.columns.str.replace(r'[^a-zA-Z0-9]+', '_', regex=True).str.strip('_')

In [35]:
df.columns

Index(['freelancer_id', 'name', 'gender', 'age', 'country', 'language',
       'primary_skill', 'years_of_experience', 'hourly_rate_usd', 'rating',
       'is_active', 'client_satisfaction'],
      dtype='str')

In [36]:
df['hourly_rate_usd'] = pd.to_numeric(
    df['hourly_rate_usd'],
    errors='coerce'
)

In [37]:
df['client_satisfaction'] = (
    df['client_satisfaction']
    .astype(str)
    .str.replace('%', '', regex=False)
)

In [38]:
df['client_satisfaction'] = pd.to_numeric(
    df['client_satisfaction'],
    errors='coerce'
)

In [39]:
df['age'] = df['age'].fillna(df['age'].median())

In [40]:
df['years_of_experience'] = df['years_of_experience'].fillna(
    df['years_of_experience'].median()
)

In [41]:
df['hourly_rate_usd'] = df['hourly_rate_usd'].fillna(
    df['hourly_rate_usd'].median()
)

In [42]:
df['rating'] = df['rating'].fillna(
    df['rating'].median()
)

In [43]:
df['client_satisfaction'] = df['client_satisfaction'].fillna(
    df['client_satisfaction'].median()
)

In [44]:
df['is_active'] = df['is_active'].astype(str).str.strip().str.lower()

In [45]:
df['is_active'] = df['is_active'].replace({
    'y': 1,
    'yes': 1,
    'true': 1,
    '1': 1,
    'n': 0,
    'no': 0,
    'false': 0,
    '0': 0,
    'nan': np.nan
})

In [46]:
df['is_active'] = df['is_active'].fillna(
    df['is_active'].mode()[0]
)

In [47]:
df['is_active'].value_counts()

is_active
0    554
1    446
Name: count, dtype: int64

In [48]:
df.isnull().sum()

freelancer_id          0
name                   0
gender                 0
age                    0
country                0
language               0
primary_skill          0
years_of_experience    0
hourly_rate_usd        0
rating                 0
is_active              0
client_satisfaction    0
dtype: int64

In [49]:
df.duplicated().sum()

np.int64(0)

In [50]:
df.head()

,freelancer_id,name,gender,age,country,language,primary_skill,years_of_experience,hourly_rate_usd,rating,is_active,client_satisfaction
0,FL250001,Ms. Nicole Kidd,female,52.0,Italy,Italian,Blockchain Development,11.0,100.0,2.6,0,79.0
1,FL250002,Vanessa Garcia,female,52.0,Australia,English,Mobile Apps,34.0,50.0,3.3,1,84.0
2,FL250003,Juan Nelson,male,53.0,Germany,German,Graphic Design,31.0,50.0,0.0,0,71.0
3,FL250004,Amanda Spencer,female,38.0,Australia,English,Web Development,4.0,50.0,1.5,0,90.0
4,FL250005,Lynn Curtis DDS,female,53.0,Germany,German,Web Development,27.0,30.0,4.8,0,83.0

In [51]:
df.describe()

,age,years_of_experience,hourly_rate_usd,rating,client_satisfaction
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,40.524000,11.221000,51.605000,2.521400,79.222000
std,11.762218,9.444329,18.511933,1.466572,10.434059
min,20.000000,0.000000,20.000000,0.000000,60.000000
25%,31.000000,3.000000,50.000000,1.500000,71.000000
50%,41.000000,9.000000,50.000000,2.600000,79.000000
75%,51.000000,17.000000,50.000000,3.700000,87.000000
max,60.000000,41.000000,100.000000,5.000000,100.000000

In [ ]:
# find the ouliers in the dataset using IQR method
Q1 = df['column_name'].quantile(0.25)

In [ ]:
# find the difference between unique and nunique values in the dataset